import streamlit as st
import numpy as np
from PIL import Image
import io
import time
from pipeline import RadVerifyPipeline

# Set page configuration for a professional medical look
st.set_page_config(
    page_title="RadVerify - AI Analysis",
    page_icon="🩺",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for medical theme
st.markdown("""
    <style>
    .main {
        background-color: #f8f9fa;
    }
    .stMetric {
        background-color: #ffffff;
        padding: 15px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    }
    .report-card {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        border-left: 5px solid #007bff;
        margin-bottom: 20px;
    }
    .comparison-table {
        font-family: monospace;
        white-space: pre;
        background-color: #1e1e1e;
        color: #d4d4d4;
        padding: 10px;
        border-radius: 5px;
        overflow-x: auto;
    }
    </style>
    """, unsafe_allow_html=True)

# Sidebar - Configuration
with st.sidebar:
    st.title("⚙️ Settings")
    enhance_image = st.toggle("Enhance Image Quality", value=True)
    st.divider()
    st.markdown("### 🔬 Model Info")
    st.info("EfficientNet-B0 + U-Net Masking + LLM")
    st.caption("Version: 1.2.0-AdvancedAI")

# Header Section
st.title("🩺 RadVerify")
st.subheader("Advanced Radiology Report Verification System")
st.markdown("Verifying fetal ultrasound scans with deep learning and computer vision.")

# Input Section
col1, col2 = st.columns([1, 1.2])

with col1:
    st.markdown("### 📤 Upload Medical Scan")
    uploaded_file = st.file_uploader("Select Ultrasound Image (JPG/PNG)", type=["jpg", "png", "jpeg"])
    if uploaded_file:
        st.image(uploaded_file, caption="Original Scan", use_column_width=True)

with col2:
    st.markdown("### 📝 Paste Radiology Report")
    report_text = st.text_area("Enter doctor's findings text", height=300, 
                              placeholder="Fetal biometry: BPD 47mm, HC 175mm, AC 150mm, FL 32mm...")

# Verify Button
if st.button("🔍 Run Full Verification", disabled=not (uploaded_file and report_text)):
    pipeline = RadVerifyPipeline()
    
    with st.spinner("Executing 9-stage verification pipeline..."):
        # Process the image and report
        results = pipeline.process(
            image_file=uploaded_file,
            doctor_report_text=report_text,
            enhance_image=enhance_image
        )
        
    if results['success']:
        st.success("Analysis Complete!")
        
        # Dashboard Overview
        st.divider()
        st.header("📊 Verification Dashboard")
        
        m1, m2, m3, m4 = st.columns(4)
        agreement = results['verification_results']['agreement_rate'] * 100
        risk = results['verification_results']['risk_level'].upper()
        
        # Extract pixel_to_mm if available (it might be in ai_findings or calculated in analyze)
        pixel_to_mm = results['ai_findings'].get('pixel_to_mm', 0.25)
        
        m1.metric("Agreement Rate", f"{agreement:.1f}%")
        m2.metric("Risk Level", risk)
        m3.metric("Calibration", f"{pixel_to_mm:.4f} mm/px")
        m4.metric("GA Estimate", f"{results['ai_findings']['gestational_age_estimate']['weeks']}w {results['ai_findings']['gestational_age_estimate']['days']}d")

        # Tabs for detailed results
        tab1, tab2, tab3, tab4 = st.tabs(["📄 Comparison Report", "📝 Medical Narrative", "🤖 AI Findings", "📷 Image Processing"])
        
        with tab1:
            st.markdown("### Side-by-Side Comparison")
            st.markdown(f"```\n{results['comparison_report_text']}\n```")

        with tab2:
            st.markdown("### AI-Synthesized Narrative")
            st.info("This report is generated by analyzing segmentations and biometric trends.")
            st.markdown(results.get('medical_narrative', "Narrative processing failed."))
            
        with tab3:
            st.markdown("### AI Analysis Details")
            col_a, col_b = st.columns(2)
            with col_a:
                st.write("**Biometric Measurements (CV):**")
                for param, data in results['ai_findings']['biometry'].items():
                    st.write(f"- **{param}**: {data['value']} {data['unit']} ({data['method']})")
            with col_b:
                st.write("**Image Quality Score:**")
                quality = results['ai_findings']['overall_quality'].upper()
                st.info(f"Quality: {quality}")
                
        with tab3:
            st.markdown("### Image Enhancement Summary")
            proc_col1, proc_col2 = st.columns(2)
            with proc_col1:
                if results['enhanced_image'] is not None:
                    st.image(results['enhanced_image'], caption="Enhanced Scan", use_column_width=True)
            with proc_col2:
                if results.get('enhancement_metrics'):
                    st.write("**Enhancement Metrics:**")
                    st.write(f"- PSNR: {results['enhancement_metrics']['psnr']:.2f}")
                    st.write(f"- Sharpness: +{results['enhancement_metrics']['sharpness_improvement']:.1f}%")
                st.write("**Preprocessing Metadata:**")
                st.json(results['preprocessing_metadata'])

        # Final Summary
        st.divider()
        st.markdown(results['final_results']['summary'])
        
    else:
        st.error(f"Pipeline Failed at stage: {results['stage']}")
        for err in results['errors']:
            st.write(f"- {err}")

# Footer
st.divider()
st.caption("⚠️ RESEARCH PROJECT: Not for real medical diagnosis. All findings must be reviewed by qualified professionals.")